### ISSUE TITLE
Exclude "Other SVG implementations" IDL block from SVG

### ISSUE THREAD

**Issue by foolip** [tidoust/reffy#123]
https://svgwg.org/svg2-draft/struct.html#DOMInterfaces has an IDL block for implementation which don't implement HTML. In the source, it's annotated with `class="idl extract"`.

However, it appears that for SVG the IDL index is used:
https://github.com/tidoust/reffy/blob/1d58358ad7030e1f953ea055fbae8b864594f581/src/cli/extract-webidl.js#L98

(Disclaimer: I can't find "chapter-idl" in the SVG spec.)

Found via https://github.com/web-platform-tests/wpt/pull/12799#issuecomment-418113455.

**Comment by tidoust** [comment]
> https://svgwg.org/svg2-draft/struct.html#DOMInterfaces has an IDL block for implementation which don't implement HTML. In the source, it's annotated with class="idl extract".

I'm not sure what that `extract` is supposed to mean but something drops it along the way. It does not appear in the final document.

> (Disclaimer: I can't find "chapter-idl" in the SVG spec.)

It is in the single page version of the spec: https://svgwg.org/svg2-draft/single-page.html#chapter-idl

Reffy retrieves the initial page, detects that there is a link to a "single page version" and parses that version instead, not to have to deal with multiple pages.

I guess we'll have to add a hack that detects the `// must only be implemented in certain implementations` comment and drops the definition that appears right after it. That's not ideal, but I don't see any other obvious way to exclude the IDL content.

**Comment by foolip** [comment]
> Reffy retrieves the initial page, detects that there is a link to a "single page version" and parses that version instead, not to have to deal with multiple pages.

Ah. I looked at the resulting SVG.idl and saw the URL https://svgwg.org/svg2-draft/ so thought multipage must have been scraped, somehow. Is it a bug that the final URL isn't used?

I also can't find `extract` in the output. @saschanaz do you know how it's used, should it be in the output?

It seems like what's needed is an attribute that means "not for browsers". @tidoust, have you come across a situation like this in any other spec, and how was it resolved?

**Comment by AmeliaBR** [comment]
I can't figure out where in the Reffy code you are looking for an `extract` class, but as soon as https://github.com/w3c/svgwg/pull/539 is merged, it will be there.

But if there is a _better_ way for the SVG spec to mark up conditional or example IDL fragments, please let me know ASAP & I can implement that instead.

**Comment by saschanaz** [comment]
>should it be in the output?

Yes, but a build error from SVG side prevented it. https://github.com/w3c/svgwg/pull/539 will fix it as @AmeliaBR said.

**Comment by tidoust** [comment]
> Ah. I looked at the resulting SVG.idl and saw the URL https://svgwg.org/svg2-draft/ so thought multipage must have been scraped, somehow. Is it a bug that the final URL isn't used?

It still seems correct to me in the sense that it represents the URL of the latest Editor's Draft, which is what Reffy is trying to crawl, with the single page version being merely a convenient representation of that document. But I'm happy to change the URL in the IDL export if you feel that's needed.

> It seems like what's needed is an attribute that means "not for browsers". @tidoust, have you come across a situation like this in any other spec, and how was it resolved?

The other similar situation that comes to mind is the IDL defined in the [Presentation API](https://w3c.github.io/presentation-api/). That spec defines [two conformance classes](https://w3c.github.io/presentation-api/#conformance-classes). A controlling UA does not have to support the receiving IDL, and a receiving UA does not have to support the controlling IDL.

That situation hasn't really been solved: in practice, the [IDL extract](https://github.com/web-platform-tests/wpt/blob/master/interfaces/presentation-api.idl) contains the entire IDL. It so happens that the existing controlling implementation in Chrome also acts as receiver, so that does not create any real practical issue for now.

**Comment by foolip** [comment]
> It still seems correct to me in the sense that it represents the URL of the latest Editor's Draft, which is what Reffy is trying to crawl, with the single page version being merely a convenient representation of that document. But I'm happy to change the URL in the IDL export if you feel that's needed.

Nah, it's fine if you don't consider it a bug :)

The Presentation API case is interesting. But if it's not a problem in practice yet, we don't need to design a fix for it. And this SVG case will be fixed on the SVG side.

**Comment by tidoust** [comment]
I believe that issue is no longer current. Reffy includes the logic needed to exclude IDL snippets marked with an `extract` class. That said, most of the time, Reffy will simply get the IDL from the IDL index at the end of documents, assuming that it is correctly generated.
