### ISSUE TITLE
css-pseudo.idl not updated after spec change

### ISSUE THREAD

**Issue by foolip** [tidoust/reffy#141]
The change in https://github.com/w3c/csswg-drafts/pull/2573 is now visible at https://drafts.csswg.org/css-pseudo-4/#CSSPseudoElement-interface, but https://github.com/tidoust/reffy-reports/blob/master/w3c/idl/css-pseudo.idl has not been updated.

@dontcallmedom are the logs from each reffy run published somewhere, is there a list of specs that weren't successfully scraped that you have to keep on top of?

**Comment by foolip** [comment]
@tidoust could you take a look at this? It seems like some other specs aren't updating either, these PRs haven't reached reffy-reports:
https://github.com/w3c/ServiceWorker/pull/1309
https://github.com/w3c/pointerevents/pull/275
https://github.com/w3c/touch-events/pull/103

**Comment by tidoust** [comment]
Main issue should now have been fixed and IDL extracts mentioned above have now all been updated. Closing this issue as a result.

I note Reffy's instance on W3C server still fails to crawl the HTML spec though (tracked in #145). I'm still planning to have Reffy run as a Travis CI job (see #146) so that we can detect failures more easily and have access to logs.
