### ISSUE TITLE
webrtc.idl has weird "tests: 1" and "🔒" contents

### ISSUE THREAD

**Issue by foolip** [tidoust/reffy#181]
https://github.com/tidoust/reffy-reports/commit/5c12e16ccd0d56dd7def52be0ae88e0a04c77658 introduced some non-IDL into webrtc.idl.

@tidoust can you investigate?

Spotted in https://github.com/web-platform-tests/wpt/pull/19340.

**Comment by tidoust** [comment]
This was due to test annotations, which create a `details` element within the IDL extract. The switch to the latest version of Respec yesterday probably triggered the bug, although I'm actually surprised that we didn't bump into this issue before (Respec feature and relevant bits in the spec don't seem to have changed recently). Reffy should now exclude these annotations when it extracts the IDL.

@dontcallmedom, note that the test annotations next to the [definition of `RTCPeerConnection`](https://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection) look clunky. I don't know whether that should be viewed as:
- a bug in Respec, as in "Respec shouldn't add a `details` element within a `pre`"
- a style bug
- a bug in the spec itself as in "IDL definitions should not have `data-tests` attributes", noting that [Respec doc](https://github.com/w3c/respec/wiki/data-tests) on `data-tests` recommends use within `<p>` and `<li>`.
