### ISSUE TITLE
Extract normative/informative references from a BikeShed spec

### ISSUE THREAD

**Issue by tidoust** [tidoust/reffy#2]
Given the URL of a document generated with BikeShed, the goal is to extract the list of specs that this document references normatively/informatively and to produce a JSON structure with that list.

References should be identified with their ID in specref whenever possible.

Note one potential difficulty is that the starting point is not the source document, but rather the generated one.

**Comment by dontcallmedom** [comment]
I have pushed a first script that does the job; I'm working on the generated output rather than the source bikeshed for two main reasons:
* it's easier to find (since that's the one that's linked from other specs)
* it's much easier to parse - bikeshed documents can be written in markdown, and in any case, extracting the references even from a regular html-bikeshed doc is harder unless we were to import bikeshed itself
