### ISSUE TITLE
Invalid JSON produced in reffy-reports

### ISSUE THREAD

**Issue by foolip** [tidoust/reffy#219]
https://github.com/tidoust/reffy-reports/commit/44cfbb4fc08131177b1cd377551746c91d7b44c9 broke ed/css/css-conditional.json in reffy-reports, making it no longer valid JSON.

This was the first update made using reffy commit 5414c43af99852c5b9dd228f01d7bb5a8730863e and the recent changes then mighty have clues:
https://github.com/tidoust/reffy/commits/5414c43af99852c5b9dd228f01d7bb5a8730863e

https://github.com/tidoust/reffy/pull/179 seems like the most plausible cause to me.

@tidoust

**Comment by foolip** [comment]
It's suspicious that the file is 634 bytes both before and after the change, and that the first 16 lines after the corruption are valid JSON. It looks a bit like only the first part of the file was modified. It doesn't look like that's the default behavior of https://nodejs.org/api/fs.html#fs_fs_writefile_file_data_options_callback however...

**Comment by tidoust** [comment]
I'm a bit lost here. As far as I can tell, the [`ed/css/css-break.json`](https://github.com/tidoust/reffy-reports/blob/master/ed/css/css-break.json) file is a valid JSON file and its size is 3.01KB. What am I missing?

**Comment by tidoust** [comment]
Ah, it's not `css-break.json` but rather `css-conditional.json`. I'll look into it.

**Comment by foolip** [comment]
Sorry, I pasted the wrong name!

**Comment by tidoust** [comment]
What happens is the following:
- Reffy crawls [CSS Conditional Level 3](https://www.w3.org/TR/css3-conditional/) and [CSS Conditional Level 4](https://drafts.csswg.org/css-conditional-4/). It makes sense to crawl both specs because level 4 is currently written as a delta spec, so core definitions are in level 3.
- Given that exported files do not include any level indication, when two specs lead to the same filename (here `css-conditional`), rule is to only export the latest level (that means we don't export all definitions, but it's hard to do anything better unless we add the notion of delta specs somewhere, see #117).
- That rule works provided the code manages to determine which level is which. In this case, Level 3 still uses the "old" URL pattern with a `css3-conditional` shortname. Code fails to detect that this means level 3 and fails to detect that it is in the "two levels" situation.
- We end up with two `writeFile` commands issued against the same file at the same time, which explains the weird output.

I'll make sure such clashes can no longer happen.

**Comment by foolip** [comment]
Yay, thanks for the detailed explanation and fix, @tidoust!
