### ISSUE TITLE
crawl.json has edDraft is not the final redirected URL

### ISSUE THREAD

**Issue by foolip** [tidoust/reffy#220]
https://raw.githubusercontent.com/tidoust/reffy-reports/47284896c74598be0deaeeb85975aed60853cf56/ed/crawl.json has the URL https://w3c.github.io/webcrypto/Overview.html for `edDraft` and `crawled` for  https://www.w3.org/TR/WebCryptoAPI/.

At least `crawled` should be just https://w3c.github.io/webcrypto/ because https://w3c.github.io/webcrypto/Overview.html redirects there.

This may be fixed by https://github.com/tidoust/reffy/issues/131, although there's both a  `<meta http-equiv="Refresh">` and a script involved:
```html
 <!DOCTYPE html>
<html>
<head>
  <title>Web Crypto</title>
  <meta charset='utf-8'>
  <meta http-equiv="Refresh" content="5; URL=http://w3c.github.io/webcrypto/">
</head>
<body>
  <section id='sotd'>
    <p>We moved! Go to <a href="http://w3c.github.io/webcrypto/">http://w3c.github.io/webcrypto/</a> instead.</p>
  </section>
  <script>
   var newlocation = "http://w3c.github.io/webcrypto/" + window.location.hash;
   window.location = newlocation;
  </script>
</body>
</html>
```

**Comment by tidoust** [comment]
I agree it would make sense to have `crawled` reflect the URL of the actual content having been processed. Among other things, this could help spot situations where we missed a redirect. This is independent of support for redirects in itself, we just need to keep track of the redirected URL (which currently gets lost in [`loadSpecificationFromHtml`](https://github.com/tidoust/reffy/blob/master/src/lib/util.js#L56)).

I note that the [report generator](https://github.com/tidoust/reffy/blob/master/src/cli/generate-report.js#L73) uses the `crawled` info to tell which version the crawler processed, and thus expects `crawled` to match `edDraft` when the Editor's Draft was processed. That said, this info can be determined otherwise (`crawl.json` starts with an `options` object which lists crawl options, no need to check specs individually to know that crawl was done on editor's drafts).

**Comment by tidoust** [comment]
The redirected URL now appears in the crawl results (and the IDL extracts).
