### ISSUE TITLE
Report invalid CSS Value Definition Syntax

### ISSUE THREAD

**Issue by pyoor** [tidoust/reffy#327]
One of the most common issues I've found in when parsing these specifications is that the CSS value definition is incorrect.  Often times this is due to the lack of quotes around CSS properties (as opposed to CSS Types).

An example of this can be seen here:
https://github.com/w3c/csswg-drafts/issues/5222

I believe that reffy could easily be modified to report these errors.  After parsing the spec, all definitions could be combined into a single grammar and parsed to determine if any of the rules include an invalid reference.

Is this something you'd consider adding or would be open to?

**Comment by tidoust** [comment]
First, I note that we ran that exercise some time ago and reported potentially problematic specs to the CSS WG (as you did with CSS Speech), see #110. The list most likely needs to be updated (some of these have been fixed since we last looked at it, and there must be new ones to add...)

It would be good to report these errors directly. Our current focus is not really on CSS syntax for the time being. If you are open to contributing, we'd definitely be open to reviewing ;)

The "missing CSS rules" file probably needs to be revisited too:
https://github.com/tidoust/reffy/blob/master/src/specs/missing-css-rules.json

PS: More generally, we're trying to consolidate the code into logical components and would be very interested to learn about existing usage of the code and/or of the reports. If you can share the context that leads you to look into Reffy's reports, either here or privately (fd@w3.org), that would be great. It is, obviously, totally fine if you cannot or do not want to!

**Comment by pyoor** [comment]
Unfortunately my project that leverages reffy is not public at this time.  However, in it's simplest form, we're using reffy to extract the CSS value definitions from the specs and for use with [css-tree](https://github.com/csstree/csstree).

I think that I could apply the syntax validation code to reffy fairly easily.  I'll try and take a look at it in the next week or two and if so, send you a PR.  In the meantime, I'll go ahead and close this issue.

Thanks!
